"""Add description column to Room table

Revision ID: 000fb491b666
Revises: 15c25c779794
Create Date: 2026-03-21 16:00:56.151769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000fb491b666'
down_revision = '15c25c779794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
