"""add hostel_id to announcements

Revision ID: 431537b86124
Revises: d65b4d93dcb4
Create Date: 2026-04-03 20:08:29.562143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431537b86124'
down_revision = 'd65b4d93dcb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hostel_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_announcements_hostel_id_hostels'), 'hostels', ['hostel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_announcements_hostel_id_hostels'), type_='foreignkey')
        batch_op.drop_column('hostel_id')

    # ### end Alembic commands ###
